name: CI/CD Node.js 18

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1 : Vérification et préparation (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installation des dépendances
        run: npm install

      # On sauvegarde les fichiers du projet pour le job suivant
      - name: Upload du projet
        uses: actions/upload-artifact@v4
        with:
          name: node-project-files
          path: .

  # JOB 2 : Construction Docker et Push (Docker)
  docker:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build # Ce job attend obligatoirement la réussite du job 'build'
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Récupération des fichiers du projet
        uses: actions/download-artifact@v4
        with:
          name: node-project-files

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          # On réutilise les secrets créés pour le TP Spring Boot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image
        run: |
          # Construction avec le tag latest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app-sofiane:latest .
          # Envoi vers Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app-sofiane:latest
